version: "3.9"

services: 
  redis: 
    image: redis
    volumes: 
      - caching:/redis/db
    container_name: redis
  
  server:
    build: .
    volumes: 
      - /C/Users/ASUS/.aws/:/root/.aws:ro
    ports:
      - 80:80
    container_name: server
    depends_on:
      - redis

volumes: 
  caching: